# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update README.md

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  schedule:
    - cron: "* * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name yoshemith
        git config user.email cv3227@innovaccion.mx
        git add README.md
        git commit -m "[bot] Update README with latest tweet"
        git push origin main
